[package]
name = "kmux-desktop"
version = "0.1.0"
description = "Desktop manager for kmux SSH identities"
authors = ["Otavio Gonzaga <otaviolgonzaga@gmail.com>"]
edition = "2024"
rust-version = "1.89"
categories = ["command-line-utilities", "authentication"]
keywords = ["ssh", "agent", "security"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "kmux_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
kmux = { package = "ssh-kmux", git = "https://github.com/OtavioGonzaga/kmux", rev = "583b5d77a49da655184a158bc442dd24a055a5d3" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
